Repository hashicorp/packer-plugin-vmware, pull requests merged in 2024-08, with the labels that each got.

#230 docs: update layouts
  .web-docs/components/builder/iso/README.md
  .web-docs/components/builder/vmx/README.md
  builder/vmware/common/driver_config.go
  builder/vmware/iso/config.hcl2spec.go
  builder/vmware/vmx/config.hcl2spec.go
  docs-partials/builder/vmware/Footnotes.mdx
  docs-partials/builder/vmware/RemoteHypervisorBuilds.mdx
  docs-partials/builder/vmware/SshKeyPairAutomation.mdx
  docs-partials/builder/vmware/VncPortDiscovery.mdx
  docs-partials/builder/vmware/common/DriverConfig-not-required.mdx
  docs/builders/iso.mdx
  docs/builders/vmx.mdx
Labels: documentation

#219 refactor: tools upload flavors
  .web-docs/components/builder/iso/README.md
  .web-docs/components/builder/vmx/README.md
  builder/vmware/common/step_upload_tools.go
  builder/vmware/common/tools_config.go
  builder/vmware/iso/testdata/minimal.json
  docs-partials/builder/vmware/common/ToolsConfig-not-required.mdx
Labels: tech-debt

#234 chore: v1.1.0 dev
  version/version.go
Labels: chore

#201 feat: check ovftool version
  builder/vmware/common/driver.go
  builder/vmware/common/driver_esx5.go
  builder/vmware/common/step_export.go
Labels: documentation, enhancement

#235 Release 1.1.0
  version/version.go
Labels: ignore-for-release

#240 chore: update `driver_config.go`
  .web-docs/components/builder/iso/README.md
  .web-docs/components/builder/vmx/README.md
  builder/vmware/common/driver_config.go
  builder/vmware/common/driver_config_test.go
  docs-partials/builder/vmware/common/DriverConfig-not-required.mdx
Labels: tech-debt, chore

#239 chore: error technical debt
  .web-docs/components/builder/vmx/README.md
  builder/vmware/common/driver.go
  builder/vmware/common/driver_esx5.go
  builder/vmware/common/driver_esx5_test.go
  builder/vmware/common/driver_fusion6.go
  builder/vmware/common/driver_parser.go
  builder/vmware/common/driver_parser_test.go
  builder/vmware/common/run_config.go
  builder/vmware/common/run_config_test.go
  builder/vmware/common/ssh.go
  builder/vmware/common/step_clean_files.go
  builder/vmware/common/step_configure_vmx.go
  builder/vmware/common/step_configure_vmx_test.go
  builder/vmware/common/step_configure_vnc.go
  builder/vmware/common/step_create_disks.go
  builder/vmware/common/step_export.go
  builder/vmware/common/step_http_ip_discover.go
  builder/vmware/common/step_register.go
  builder/vmware/common/step_remote_upload.go
  builder/vmware/common/step_run.go
  builder/vmware/common/step_shutdown.go
  builder/vmware/common/step_suppress_messages.go
  builder/vmware/common/step_upload_tools.go
  builder/vmware/common/step_upload_vmx.go
  builder/vmware/common/step_vnc_boot_command.go
  builder/vmware/common/step_vnc_connect.go
  builder/vmware/common/tools_config.go
  builder/vmware/iso/step_create_vmx.go
  builder/vmware/iso/step_create_vmx_test.go
  builder/vmware/vmx/config.go
  builder/vmware/vmx/step_clone_vmx.go
  docs-partials/builder/vmware/vmx/Config-not-required.mdx
Labels: tech-debt, chore

#238 chore(ci): add codeql analysis
  .github/workflows/codeql-analysis.yml
  README.md
  go.mod
Labels: chore

#245 chore: address parsing
  builder/vmware/common/driver_parser.go
Labels: tech-debt, security, chore

#210 refactor: update `esx5` to `esxi`
  .web-docs/components/builder/iso/README.md
  .web-docs/components/builder/vmx/README.md
  builder/vmware/common/driver.go
  builder/vmware/common/driver_config.go
  builder/vmware/common/driver_config_test.go
  builder/vmware/common/driver_esxi.go
  builder/vmware/common/driver_esxi_test.go
  builder/vmware/common/output_dir.go
  builder/vmware/common/run_config_test.go
  builder/vmware/common/step_export.go
  builder/vmware/common/step_export_test.go
  builder/vmware/common/step_output_dir_test.go
  builder/vmware/common/step_prepare_tools.go
  builder/vmware/common/step_prepare_tools_test.go
  builder/vmware/common/step_remote_upload.go
  builder/vmware/common/step_upload_tools.go
  builder/vmware/common/step_upload_vmx.go
  builder/vmware/common/step_vnc_connect.go
  builder/vmware/common/tools_config.go
  builder/vmware/iso/builder_test.go
  builder/vmware/iso/config.go
  builder/vmware/vmx/config.go
  builder/vmware/vmx/config_test.go
  docs-partials/builder/vmware/common/DriverConfig-not-required.mdx
  docs-partials/builder/vmware/common/ToolsConfig-not-required.mdx
Labels: tech-debt, hypervisor/esxi
