Repository hashicorp/packer-plugin-vmware, pull requests merged in 2025-08, with the labels that each got.

#334 version: prepare v2.0.0-dev
  version/version.go
Labels: chore

#335 chore: remove workstation player support
  .web-docs/README.md
  .web-docs/components/builder/iso/README.md
  .web-docs/components/builder/vmx/README.md
  README.md
  builder/vmware/common/driver.go
  builder/vmware/common/driver_player.go
  builder/vmware/common/driver_player_unix.go
  builder/vmware/common/driver_player_windows.go
  docs-partials/builder/vmware/Footnotes.mdx
  docs/README.md
Labels: version/bump major, chore

#338 refactor: fusion constants
  .web-docs/components/builder/iso/README.md
  .web-docs/components/builder/vmx/README.md
  builder/vmware/common/driver.go
  builder/vmware/common/driver_config.go
  docs-partials/builder/vmware/common/DriverConfig-not-required.mdx
Labels: tech-debt, refactor

#341 refactor: remove `ssh_skip_request_pty`
  builder/vmware/common/ssh_config.go
  builder/vmware/iso/config.hcl2spec.go
  builder/vmware/vmx/config.hcl2spec.go
Labels: tech-debt, version/bump major, refactor

#342 refactor: enforce minimum ovftool version
  builder/vmware/common/driver.go
Labels: tech-debt, version/bump major, refactor

#343 refactor: consolidate testdata paths
  builder/vmware/common/testdata/floppies/bar.bat
  builder/vmware/common/testdata/floppies/foo.ps1
  builder/vmware/common/testdata/http/preseed.cfg
  builder/vmware/common/testdata/minimal.json
  builder/vmware/iso/builder_acc_test.go
  builder/vmware/iso/builder_test.go
  builder/vmware/vmx/builder_test.go
  builder/vmware/vmx/testdata/floppies/bar.bat
  builder/vmware/vmx/testdata/floppies/foo.ps1
Labels: tech-debt, refactor

#347 chore: remove snake case
  builder/vmware/common/driver_workstation.go
Labels: tech-debt, chore

#348 refactor: centralize allowed values and constants
  builder/vmware/common/driver.go
  builder/vmware/common/export_config.go
  builder/vmware/common/hw_config.go
  builder/vmware/common/step_clean_files.go
  builder/vmware/common/tools_config.go
  builder/vmware/iso/config.go
  builder/vmware/vmx/config.go
Labels: tech-debt, refactor

#349 refactor: naming prefix constant
  builder/vmware/common/driver.go
  builder/vmware/common/step_clean_files.go
  builder/vmware/iso/config.go
  builder/vmware/vmx/config.go
Labels: tech-debt, refactor

#350 refactor: os checks
  builder/vmware/common/driver.go
  builder/vmware/common/driver_workstation.go
  builder/vmware/common/driver_workstation_unix.go
  builder/vmware/common/hw_config.go
  builder/vmware/common/tools_config_test.go
Labels: tech-debt, refactor

#351 chore: Improve builder clarity
  builder/vmware/iso/builder.go
  builder/vmware/vmx/builder.go
Labels: tech-debt, chore

#352 refactor: align receiver variables
  builder/vmware/common/driver_parser.go
Labels: tech-debt, refactor

#356 chore: remove outdated fixme comments
  builder/vmware/iso/step_create_vmx.go
Labels: tech-debt, chore

#358 chore: correct typos and grammar
  .web-docs/components/builder/vmx/README.md
  README.md
  builder/vmware/common/driver.go
  docs/builders/vmx.mdx
Labels: tech-debt, chore

#359 refactor: Improve file handling and logging
  builder/vmware/common/driver.go
  builder/vmware/iso/step_create_vmx.go
Labels: tech-debt, refactor

#360 refctor: move hardware version constants
  builder/vmware/common/driver.go
  builder/vmware/iso/builder_test.go
  builder/vmware/iso/config.go
Labels: tech-debt, refactor

#355 chore: yaml formatting in ci and release
  .github/actions/build-and-persist-plugin-binary/action.yml
  .github/release.yml
  .github/workflows/build_plugin_binaries.yml
  .goreleaser.yml
Labels: tech-debt, chore

#375 fix: attach custom cd for `cd_files`
  .web-docs/components/builder/vmx/README.md
  builder/vmware/common/step_configure_vmx.go
  builder/vmware/common/step_configure_vmx_test.go
  builder/vmware/vmx/builder.go
  builder/vmware/vmx/config.go
  builder/vmware/vmx/config.hcl2spec.go
  docs-partials/builder/vmware/vmx/Config-not-required.mdx
Labels: bug

#376 refactor: update network adapter type validation
  builder/vmware/common/hw_config.go
  builder/vmware/common/hw_config_test.go
  builder/vmware/iso/builder_test.go
Labels: tech-debt, refactor

#367 chore: update examples
  example/README.md
  example/build.pkr.hcl
  example/data/debian/preseed.pkrtpl.hcl
  example/pkrvars/debian/fusion-12.pkrvars.hcl
  example/pkrvars/debian/fusion-amd64.pkrvars.hcl
  example/pkrvars/debian/fusion-arm64.pkrvars.hcl
  example/pkrvars/debian/workstation-amd64.pkrvars.hcl
  example/sources.pkr.hcl
  example/variables.pkr.hcl
Labels: tech-debt, chore

#370 chore: update virtual hardware versions
  .web-docs/components/builder/iso/README.md
  builder/vmware/common/driver.go
  builder/vmware/iso/config.go
  docs-partials/builder/vmware/iso/Config-not-required.mdx
Labels: version/bump major, chore

#363 refactor: default guest os type based on architecture
  .web-docs/components/builder/iso/README.md
  builder/vmware/common/driver.go
  builder/vmware/iso/config.go
  docs-partials/builder/vmware/iso/Config-not-required.mdx
Labels: tech-debt, version/bump major, refactor
